#!/bin/bash
#hakase-helper
#hakase installer script

#config
directory=$HOME/hakase
#install=/usr/local/bin/hakase
install=$directory/hakase
#if there's no hakase home directory, make it and days and a working file
if [ ! -d $directory ]
then
	echo "making hakase directory"
	mkdir $directory
	mkdir $directory/days
	cp template.hake $directory/working.hake
fi

#copy most current template
echo "copying most current template"
cp template.hake $directory/template.hake

#copy most current hakase and make it executable
echo "copying most current version of hakase"
cp hakase $install
chmod +x $install

#add hakase to zshrc or bashrc
if [ -z $HOME/.hakasewashere ]
then
	if [ -e $HOME/.zshrc ]
	then
		echo "alias hakase=\"$directory/hakase\"" >> $HOME/.zshrc
		touch $HOME/.hakasewashere
		echo "adding hakase to zshrc"
	elif [ -e $HOME/.bashrc ]
	then
		echo "alias hakase=\"$directory/hakase\"" >> $HOME/.zshrc
		touch $HOME/.hakasewashere
		echo "adding hakase to bashrc"
	fi
else
	echo "already added to config"
fi
echo "DONE"
