#!/bin/bash
#hakase v0.3.0

#config
#source config from hakase.config, normally in the ~/hakase/ folder (as installed by helper)
. $HOME/hakase/hakase.config

#code
first=$( echo $1 | tr '[:upper:]' '[:lower:]' )
second=$2

case $first in
	"")
		$editor $editorSettings $working
		;;
	copy)
		case $second in
			"")
				cp $working $archive/$dateFormat.hake && echo "Current log archived as $dateFormat"
				;;
			*)
				cp $working $archive/$second.hake && echo "Current log archived as $second"
				;;
		esac
		;;
	fresh)
		second=$( echo $second | tr '[:upper:]' '[:lower:]' )
		case $second in
			"")
				#still working on carryover
				cp $working $save
				cp $template $working && echo "Loading '$template' over '$working'"
				sed -i '' "1s/^/$dateFormat/" $working
				;;			
			nocarry)
				cp $working $save
				cp $template $working && echo "Loading '$template' over '$working'"
				sed -i '' "1s/^/$dateFormat/" $working
				;;
			*)
				echo "Sorry, fresh doesn't have that verb available"
				;;
		esac
		;;
	load)
		case $second in
			"")
				echo "Sorry, you need to list the file you'd like to load"
				;;
			*)
				if [ -e $archive/$second ]
				then
					cp $archive/$second $working && echo "Loading '$archive/$second' over '$working'"
				elif [ -e $archive/$second.hake ]
				then
					cp $archive/$second.hake $working && echo "Loading '$archive/$second' over '$working'"
				elif [ -e $second ]
				then
					cp $second $working && echo "Loading '$second' over '$working'"
				elif [ -e $second.hake ]
				then
					cp $second.hake $working && echo "Loading '$second.hake' over '$working'"	
				elif [ ! -e $second ]
				then
					echo "Sorry, I couldn't find $second, $second.hake, $archive/$second, or $archive/$second.hake"
				else
					echo "Sorry, that didn't work, and I don't know why"
				fi
				;;
		esac
		;;
	rank)
		echo "Sorry, rank isn't ready yet"
		;;
	*)
		echo "Sorry, I don't know how to do that verb"
		;;
esac        

